config/routes.rb
#
# this comes in handy if the current_user is needed
# request.env['warden'].user(:user)
#
Rails.application.routes.default_url_options = {
  protocol: Rails.env.development? || Rails.env.test? ? 'http' : 'https',
  host: ENV['HOST_NAME']
}

Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  use_doorkeeper

  # zapier
  authenticate(:user) do
    get '/auth-test', to: 'application#auth_test'
    get '/curators', to: 'companies#get_curators'
    get '/invitation_templates', to: 'companies#get_invitation_templates'
    # was going to do this via successes#index but zapier trigger setup was not sending ?zapier_trigger=true
    get '/win_stories', to: 'successes#zapier_trigger'
    post '/successes', to: 'successes#create', constraints: { zapier_create: 'true' }
    post '/contributions', to: 'contributions#create', constraints: { zapier_create: 'true' }
  end

  get '/sitemap', to: 'site#sitemap'
  get '/:google', to: 'site#google_verify', constraints: { google: /google\w+/ }

  # sendgrid events (currently tracking open and click)
  post '/esp/notifications', to: 'site#esp_notifications'

  # constraints(DevSubdomain) do
  #   authenticate(:user) do
  #     get '/auth-test', to: 'application#auth_test'
  #     post '/successes', to: 'successes#create', constraints: { zap: 'true' }
  #   end
  #   # need to pick up on devise routes here, without doing so explicitly
  #   # as that will conflict with devise routes declared below
  #   # 'method' instead of 'action' - latter is keyword with its own params entry
  #   devise_scope :user do
  #     get '/:devise/:method', to: 'users/sessions#new', constraints: { devise: 'users', method: 'sign_in' }
  #     post '/:devise/:method', to: 'users/sessions#create', constraints: { devise: 'users', method: 'sign_in' }
  #   end
  # end

  # valid subdomains (company/subdomain exists, excludes www)
  constraints(CompanySubdomain) do

    get '/', to: 'stories#index'

    get '/plugins/:type/cs', to: 'plugins#main'
    # get '/widgets/:type/cs', to: 'plugins#main'  # legacy (was varmour)
    get '/widget/cs', to: 'plugins#main'  # legacy (trunity)

    # specifying a default format for plugins#show because (for unknown reason) ajax jsonp
    # request sent from IE11 was resulting in request interpreted as html
    # get '/plugins/:type/show', to: 'plugins#show', as: 'plugin_view', format: 'js'
    get '/plugins/:type/show', to: 'plugins#show', as: 'plugin_view'
    get '/plugins/:type/init', to: 'plugins#init', as: 'plugin_init'
    get '/plugins/track', to: 'plugins#track'
    get '/plugins/demo', to: 'plugins#demo'

    # see below for route to public story page
    resources(:stories, { only: [:index] }) do
      get '/search', on: :collection, to: 'stories#search'
      get '/share_on_linkedin', on: :member, to: 'stories#share_on_linkedin'
    end


    # routing constraints cause issues within the devise authenticate block
    # (possible explanation? https://anadea.info/blog/rails-authentication-routing-constraints-considered-harmful)
    # => bring these routes outside the authenticate block and authenticate in the controller
    get '/:workflow_stage', to: 'companies#show',
          constraints: lambda { |params, request|
            # params[:id] = request.env['warden'].user(:user).try(:company_id).to_s
            params[:workflow_stage] =~ /prospect|curate|promote|measure/
            # params[:id].present?  # i.e. user signed in
          }, as: 'dashboard'
    # get '/curate/:customer_slug/:story_slug', to: 'stories#edit',
    #       constraints: lambda { |params, request|
    #         Customer.friendly.exists?(params[:customer_slug]) &&
    #         Story.friendly.exists?(params[:story_slug])
    #       }, as: 'curate_story'
    get '/promote/preview/:story_slug', to: 'adwords_ads#preview',
          constraints: lambda { |params, request|
            Story.friendly.exists?(params[:story_slug])
          }

    authenticate :user do

      get '/settings', to: 'companies#edit', as: 'company_settings'

      resources :companies, only: [:show, :edit, :update] do
        resources :customers, only: [:edit, :create, :update, :destroy], shallow: true
        resources :successes, except: [:index], shallow: true do
          resources :contributions, only: [:index, :new]
          resources :results, only: [:create, :destroy]
          collection { post '/import', to: 'successes#import' }
        end
        resources :stories, only: [:edit, :create, :update, :destroy], shallow: true do
          put '/create_gads', on: :member, to: 'adwords_ads#create'
          put '/update_gads', on: :member, to: 'adwords_ads#update'
        end
        # resources :stories, only: [:create]
        resources :contributions, except: [:new, :edit, :update], shallow: true do
          # need to distinguish '/contributions/:id' routes from '/contributions/:token' routes;
          # hence :update is excluded above and added below
          # (note :edit always uses '/contributions/:token/:type' route
          member do 
            put :update, constraints: { id: /\d+/ }
            patch :update, constraints: { id: /\d+/ }
          end
        end
        resources :ctas, only: [:show, :create, :update, :destroy], shallow: true
        resources :invitation_templates
        member { put :update_gads }
        member { get :set_reset_gads }
        member { get '/promote-settings', to: 'companies#show' }
        member { put :widget }
        # need :get for the sync. response (redirect_to)
        # and :put for the async. response (see companies/promote.js.erb)
        member { get '/adwords', to: 'adwords#update_company' }
        member { put '/adwords', to: 'adwords#update_company' }
        member { put '/adwords/reset', to: 'adwords#sync_company', as: 'adwords_sync' }
      end

      get '/successes', to: 'successes#index'

      # analytics
      get '/analytics/charts', to: 'analytics#charts', as: 'charts'
      get '/analytics/visitors', to: 'analytics#visitors', as: 'measure_visitors'
      get '/analytics/stories', to: 'analytics#stories', as: 'measure_stories'

      # switch to a different user (this needs to come before the next route below)
      post(
        '/user-profile', 
        to: 'profile#switch', 
        as: 'switch_user',
        constraints: -> (request) { request.params[:switch_user_id].present? }
      )
      # user profile
      get '/user-profile', to: 'profile#edit', as: 'edit_profile'

      # approval PDF
      get '/stories/:id/approval', to: 'stories#approval', as: 'story_approval'

    end

    # get '/:workflow_stage', to: 'companies#show',
    #         constraints: lambda { |params, request|
    #           params[:id] = request.env['warden'].user(:user).try(:company_id).to_s
    #           params[:workflow_stage].match(/(prospect|curate|promote|measure)/) &&
    #           params[:id].present?  # i.e. user signed in
    #         }, as: 'company_main'
    #   get '/curate/:customer_slug/:story_slug', to: 'stories#edit',
    #         constraints: lambda { |params, request|
    #           Customer.friendly.exists?(params[:customer_slug]) &&
    #           Story.friendly.exists?(params[:story_slug]) &&
    #           params[:id] = Story.friendly.find(params[:story_slug]).id
    #         }, as: 'curate_story'
    #   get '/promote/preview/:story_slug', to: 'adwords#preview',
    #         constraints: lambda { |params, request|
    #           Story.friendly.exists?(params[:story_slug]) &&
    #           params[:id] = Story.friendly.find(params[:story_slug]).id
    #         }
    #   get '/settings', to: 'companies#edit',
    #         constraints: lambda { |params, request|
    #           params[:id] = request.env['warden'].user(:user).company_id.to_s
    #           true
    #         }, as: 'company_settings'

    # token needed for access outside of user-authorized routes
    # type IN ('contribution', 'feedback', 'opt_out', 'remove')
    get '/contributions/:token/confirm', to: 'contributions#confirm_submission', as: 'confirm_submission'
    get '/contributions/:token/:type', to: 'contributions#edit', as: 'edit_contribution', constraints: { type: /(contribution|feedback)/ }
    get '/contributions/:token/:type', to: 'contributions#update', constraints: { type: /(opt_out|remove)/ }
    put '/contributions/:token', to: 'contributions#update', as: 'contributor_submission', constraints: { submission: true }

    # linkedin
    get '/user-profile/linkedin_connect', to: 'profile#linkedin_connect', as: 'linkedin_connect'
    get '/user-profile/linkedin_callback', to: 'profile#linkedin_callback'

    get '/linkedin_auth', to: 'application#linkedin_auth'


    # need to pick up on devise sign-in route here, without doing so explicitly
    # as that will conflict with devise routes declared below
    # 'method' instead of 'action' - latter is keyword with its own params entry
    devise_scope :user do
      get '/:devise/:method', to: 'users/sessions#new', constraints: { devise: 'users', method: 'sign_in' }
    end

    # public story route moved down here so it doesn't hijack any other routes via dynamic segments.
    # don't call this route 'story' or it will leave the PUT and DELETE routes (above)
    # without an alias
    constraints(StoryPathConstraint) do
      get(
        '/:customer/:product/:title',
        to: 'stories#track',
        constraints: -> (request) { request.query_parameters[:track].present? }
      )
      get(
        '/:customer/:title',
        to: 'stories#track',
          constraints: -> (request) { request.query_parameters[:track].present? }
      )
      get '/:customer/:product/:title', to: 'stories#show', as: 'public_story'
      get '/:customer/:title', to: 'stories#show', as: 'public_story_no_product'
          
      # hidden stories
      get(
        '/:random_string', 
        to: 'stories#show',

app/helpers/stories_helper.rb
module StoriesHelper

  def disallow_search_indexing?(company=nil)
    staging? || company&.subdomain == 'pixlee'
  end

  def linkedin_widget_width(window_width)
    case window_width.to_i
    when 0...370
      '340'
    when 370...500
      (window_width.to_i - 30).to_s  # 30 = padding * 2
    when 500...768
      '470'
    when 768...992
      '330'
    when 992...1200
      '360'
    else
      '436'
    end
  end

  def stories_header_title_width (company)
    if curator?(company) && current_page?(action: 'index')
      'col-sm-6'
    elsif curator?(company) && current_page(action: 'show')
      # leave room for Edit Story button
      'col-sm-5'
    elsif company.category_tags.blank? && company.product_tags.blank?
      'col-sm-6'
    else
      'col-sm-12'
    end
  end

  def curator_story_view? (company_id)
    company_curator?(company_id) && controller_name == 'stories' && action_name == 'show'
  end

  def csp_landing
    if ENV['HOST_NAME'] == 'customerstories.net'
      'https://customerstories.net'
    elsif ENV['HOST_NAME'] == 'customerstories.org'
      'https://customerstories.org'
    else
      'http://lvh.me:3000'
    end
  end

  def grid_item_link company_id, story
    if story.published?
      story.csp_story_path
    elsif company_curator? company_id
      edit_story_path story.id
    else
      "javascript:;"
    end
  end

  # this is for PDF generation
  # ref: https://github.com/mileszs/wicked_pdf/issues/36
  def embed_remote_image(url, content_type)
    asset = open(url, "r:UTF-8") { |f| f.read }
    base64 = Base64.encode64(asset.to_s).gsub(/\s+/, "")
    "data:#{content_type};base64,#{Rack::Utils.escape(base64)}"
  end

  def meta_keywords success
    keywords = success.story_categories.pluck('name').push << success.products.pluck('name')
    keywords.present? ? keywords.join(', ') : ''
  end

  def og_image(company, provider='all-providers')
    width, height = (provider == 'linkedin') ? ['300', '160'] : ['400', '400']
    # case company.subdomain
    # when 'trunity'
    #   image = (provider == 'linkedin') ? TRUNITY_300X160_URL : TRUNITY_400X400_URL
    # when 'compas'
    #   image = (provider == 'linkedin') ? COMPAS_300X160_URL : COMPAS_400X400_URL
    # when 'corefact'
    #   image = (provider == 'linkedin') ? COREFACT_300X160_URL : COREFACT_400X400_URL
    # when 'varmour'
    #   image = (provider == 'linkedin') ? VARMOUR_300X160_URL : VARMOUR_400X400_URL
    # when 'zoommarketing'
    #   image = (provider == 'linkedin') ? ZOOM_300X160_URL : ZOOM_400X400_URL
    # when 'saucelabs'
    #   image = (provider == 'linkedin') ? SAUCELABS_300X160_URL : SAUCELABS_400X400_URL
    # when 'centerforcustomerengagement'
    #   image = (provider == 'linkedin') ? CCE_300X160_URL : CCE_400X400_URL
    # when 'zeniq'
    #   image = (provider == 'linkedin') ? ZENIQ_300X160_URL : ZENIQ_400X400_URL
    # when 'retailnext'
    #   image = (provider == 'linkedin') ? RETAILNEXT_300X160_URL : RETAILNEXT_400X400_URL
    # when 'smartpaymentplan'
    #   image = (provider == 'linkedin') ? SPP_300X160_URL : SPP_400X400_URL
    # when 'pixlee'
    #   image = (provider == 'linkedin') ? SAUCELABS_300X160_URL : SAUCELABS_400X400_URL
    # else
    #   # width = '1200'
    #   # height = '630'
    #   # image = CS_FULL_LOGO_URL
    # end
    if Rails.env.development? 
      {}
    elsif %w(trunity compas corefact varmour zoommarketing saucelabs centerforcustomerengagement zeniq retailnext smartpaymentplan pixlee) 
      .include?(company.subdomain)
      { 
        image: asset_url("companies/#{company.subdomain}/#{provider == 'linkedin' ? 'og_300x160.png' : 'og_400x400.png'}"), 
        width: width, 
        height: height 
      }
    else 
      {
        image: asset_url('cs_logo_full_1200x630.png'),
        width: '1200',
        height: '630'
      }
    end
  end

  def stories_header_class(company)
    "stories-header stories-header--#{company.subdomain} stories-header--#{background_color_contrast(company.header_color_2)}"
  end

  def stories_header_custom_colors(company)
    "background-color: #{company.header_color_2}; color: #{company.header_text_color}"
  end

  def story_card_class(story, is_dashboard: false, is_plugin: false, logos_only: false, is_grayscale: false, preselected_story_id: nil)
    [
      'story-card',
      "story-card--#{story.company.subdomain}",
      "story-card--#{story.status}",
      is_dashboard ? 'story-card--dashboard story-card--small' : '',
      is_plugin ? 'story-card--plugin' : '',
      preselected_story_id == story.id ? 'cs-loaded' : '',
      logos_only ? 'story-card--logo-only' : 'story-card--card',
      is_grayscale ? 'story-card--grayscale' : '',
    ].join(' ')
  end

end

app/views/stories/edit/_curate.html.erb
<div id='curate-story-layout' class="layout layout-main-right layout-stack-sm"
    data-story-id="<%= story.try(:id) %>" data-success-id="<%= story.success.id %>" data-success-name="<%= story.success.name %>" data-customer-id="<%= story.customer.id %>" data-customer-slug="<%= story.customer.slug %>">

  <div class="col-md-3 col-sm-4 layout-sidebar">

    <%= render 'stories/edit/tabs', { tab: tab } %>

  </div>

  <div class="col-md-9 col-sm-8 layout-main">
    <div class="tab-content stacked-content">

      <div class='row' style='margin-top: -5px;'>
        <div class="col-sm-12">
          <div style='margin-bottom: 6px;'>
            <label style='margin:0'>Customer</label>&nbsp;&nbsp;&nbsp;
            <span style='font-family:"Lato";font-size:18px;color:#999'><%= story.customer.name %></span>
          </div>
          <div>
            <!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
            <label style='margin:0'>Story Title</label>&nbsp;&nbsp;&nbsp;
          <!-- no turbolinks, so linkedin widgets load properly -->
          <!-- ref: http://stackoverflow.com/questions/17600093/rails-javascript-not-loading-after-clicking-through-link-to-helper -->
            <a href="<%= story.csp_story_path %>" class='story-title' data-turbolinks='false'
                style='font-family:"Lato";font-size:18px;color:#999'>
              <%= story.try(:title) %>
            </a>
          </div>
        </div>
      </div>

      <hr style='margin-bottom: 24px; border-top: 1px solid #e5e5e5'>

      <div id='story-settings' class="tab-pane fade <%= (tab == 'settings' || tab.nil?) ? 'in active' : '' %>">

        <%= render 'stories/edit/settings/settings',
              { company: company, story: story } %>

      </div>

      <div id='story-content' class="tab-pane fade <%= tab == 'content' ? 'in active' : '' %>">

        <%= render 'stories/edit/content/content',
              { company: company, story: story } %>

      </div>

      <div id='curate-contributors' class="tab-pane fade <%= tab == 'contributors' ? 'in active' : '' %>">

        <button type='button' style='margin:0 0 10px 0;' class='btn btn-secondary btn-sm' data-toggle='modal' data-target='#new-contributor-modal'><i class='glyphicon glyphicon-plus-sign' style='font-size:15px;top:2px'></i>&nbsp;&nbsp;&nbsp;New Contributor&nbsp;</button>

        <%= render 'companies/crowdsource/contributors/contributors_table',
              { company: company, workflow_stage: 'curate' } %>

      </div>

    </div>
  </div>

</div>

app/views/stories/edit/_edit.html.slim
#edit-story-layout {
  data-story-id=story.id
  data-success-id=story.success.id
  data-success-name=story.success.name
  data-customer-id=story.customer.id
  data-customer-slug=story.customer.slug }

  = render('stories/edit/story_header', { story: story })

  .tab-content

    #story-settings.tab-pane.fade class=('in active' if tab == '#story-settings' || tab.nil?)
      = render('stories/edit/settings/settings', { company: company, story: story })

    #story-content.tab-pane.fade class=('in active' if tab == '#story-content')
      = render('stories/edit/content/content', { company: company, story: story })

    #story-contributors.tab-pane.fade class=('in active' if tab == '#story-contributors')
      = render( \
          'companies/1_prospect/contributors/contributors_table',
          { company: company, workflow_stage: 'curate' })

app/views/stories/edit/_settings.html.erb
<%= form_for(story, url: story_path(story.id), authenticity_token: true,
      html: { method: 'put', remote: true, id: 'story-settings-form',
              class: 'directUpload',
              data: { 'form-data' => (@s3_direct_post.fields),
                      'url' => @s3_direct_post.url,
                      'host' => URI.parse(@s3_direct_post.url).host
              } }) do |f| %>

  <%= hidden_field_tag('story[form]', 'settings') %>

  <div class="row">

    <div class="col-sm-6">

      <div id='publish-control' class="form-inline">

        <div class="form-group" style='margin-right:30px'>
          <div>
            <label for="logo_published">Publish Logo</label>&nbsp;
          </div>
          <%= f.check_box(:logo_published, class: "bs-switch form-control",
                value: true) %>
        </div>

        <div class="form-group">
          <div>
            <label for='published'>Publish Story</label>&nbsp;
          </div>
          <%= f.check_box(:published, class: "bs-switch form-control") %>
        </div>
        &nbsp;
        <%= link_to('Approval PDF', story_approval_path(story.id, format: :pdf),
              id: 'approval-pdf-btn', style: 'vertical-align: bottom; ',
              data: { missing_curator_info: story.curator.missing_info.to_json,
                      missing_company_info: company.missing_info.to_json,
                      turbolinks: false },
              target: '_blank') %>

      </div>  <!-- publish control -->

      <div class="form-group required-input">
        <%= f.label(:title) %>
        <%= f.text_field(:title, class: 'form-control') %>
      </div>

      <%= render 'stories/edit/customer_logo', { story: story, f: f } %>

    </div>

    <div class="col-sm-6">

      <div class="form-group">

        <%= label_tag "category_tags[]", 'Category Tags' %>
        <!-- Note the necessary '[]' notation below  -->
        <!-- if not present, will only return a single value  -->
        <%= select_tag "category_tags[]",
            options_for_select(
              company.story_categories.present? ? company.story_categories.select_options : ['none available'],
              { selected: story.category_tags.pluck(:id),
                disabled: ['none available'] }
            ),
            { multiple: 'true', class: 'story-tags form-control', tabIndex: '-1',
              style: 'width:100%' } %>

      </div>

      <div class="form-group">

        <%= label_tag "product_tags[]", 'Product Tags' %>
        <%= select_tag "product_tags[]",
            options_for_select(
              company.products.present? ? company.products.select_options : ['none available'],
              { selected: story.product_tags.pluck(:id),
                disabled: ['none available'] }
            ),
            { multiple: 'true', class: 'story-tags form-control', tabIndex: '-1',
              style: 'width:100%' } %>

      </div>

      <div class="form-group">

        <label for="#story-ctas-select">CTAs</label>
        <%= select_tag 'ctas[]',
              grouped_options_for_select(
                company.ctas.select_options,
                { selected: story.ctas.pluck(:id), disabled: ['none available'] }
              ), { id: 'story-ctas-select', class: 'form-control', multiple: true,
                   style: 'width:100%' } %>

      </div>

    </div>

  </div>

  <hr>

  <div class="row">
    <div class="col-sm-12 text-right">
      <div class="form-group">

        <button type="reset" class="btn btn-default">Cancel</button>
        <input type='submit' class='btn btn-success' value="Save changes">

      </div>
    </div>
  </div>

<% end %>

app/views/stories/edit/_side_tabs.html.erb
<ul class="nav nav-layout-sidebar nav-stacked">

  <li>
    <a href='javascript:;'
       class='all-stories'>
      <i class='fa fa-chevron-circle-left'></i>
      &nbsp;&nbsp;All Stories
<!--       <span class='pull-right'>
      </span> -->
    </a>
  </li>

  <li class="<%= tab_select == 'story-settings' ? 'active' : (tab_select.nil? ? 'active' : '') %>">
    <a href="#story-settings" data-toggle="tab">
      <i class="fa fa-gear"></i>
      &nbsp;&nbsp;Story Settings
    </a>
  </li>

  <li class="<%= tab_select == 'story-content' ? 'active' : '' %>">
    <a href="#story-content" data-toggle="tab">
      <i class="fa fa-edit"></i>
      &nbsp;&nbsp;Story Content
    </a>
  </li>

  <li class="<%= tab_select == 'curate-contributors' ? 'active' : '' %>">
    <a href="#curate-contributors" data-toggle="tab">
      <i class="fa fa-users"></i>
      &nbsp;&nbsp;Success Contributors
    </a>
  </li>

</ul>

app/views/stories/edit/_story_header.html.slim
.story-header__wrapper

  .story-header__spacekeeper

  .story-header
    div
      span
        label Customer
      span 
        = story.customer.name
      span
        button.edit-customer.btn.btn-sm.btn-secondary {
          type="button" 
          data-customer-id=story.customer.id
          style="width: 100%" }
          i.fa.fa-fw.fa-pencil.fa-fw
          |&nbsp;&nbsp;
          |Edit Customer
    .story-header__title
      span
        label Story Title
      span 
        = story.title
      span
        = link_to( \
            "#{story.csp_story_path}?preview=true",
            { class: "btn btn-sm btn-secondary pull-right", 
              style: "width: 100%", 
              target: "_blank" }) do
          i.glyphicon.glyphicon-new-window
          |&nbsp;&nbsp;
          |View Story
    .story-header__flash class=('promote-enabled' if story.company.promote_tr?)
      p Story published successfully
      p Errors when creating Promoted Story

app/views/stories/edit/_tabs.html.erb
<ul class="nav nav-layout-sidebar nav-stacked">

  <li>
    <a href='javascript:;'
       class='all-stories'>
      <i class='fa fa-chevron-circle-left'></i>
      &nbsp;&nbsp;All Stories
<!--       <span class='pull-right'>
      </span> -->
    </a>
  </li>

  <li class="<%= tab == 'settings' ? 'active' : (tab.nil? ? 'active' : '') %>">
    <a href="#story-settings" data-toggle="tab">
      <i class="fa fa-gear"></i>
      &nbsp;&nbsp;Story Settings
    </a>
  </li>

  <li class="<%= tab == 'content' ? 'active' : '' %>">
    <a href="#story-content" data-toggle="tab">
      <i class="fa fa-pencil"></i>
      &nbsp;&nbsp;Story Content
    </a>
  </li>

  <li class="<%= tab == 'contributors' ? 'active' : '' %>">
    <a href="#curate-contributors" data-toggle="tab">
      <i class="fa fa-users"></i>
      &nbsp;&nbsp;Story Contributors
    </a>
  </li>

</ul>

app/views/stories/edit/_video.html.erb
<div class="form-group">
  <%= f.label(:video_url, 'Video URL') %>
  <%= f.text_field(:video_url, class: 'form-control',
        placeholder: 'YouTube, Vimeo, or Wistia') %>
  <%= hidden_field_tag('story[formatted_video_url]') %>
</div>

<div class="video-container text-center" style='border:1px solid #ccc;border-radius:4px;overflow:hidden'
       data-placeholder="<%= asset_path('video_placeholder.jpg') %>">

  <% if story.video_info[:provider] == 'wistia' %>

    <script src="//fast.wistia.com/embed/medias/<%= story.video_info[:id] %>.jsonp" async></script>
    <script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
    <div class="wistia_responsive_padding"
         style="padding:56.25% 0 0 0; position:relative;">
      <div class="wistia_responsive_wrapper"
           style="height:100%;left:0;position:absolute;top:0;width:100%;">
        <div class="wistia_embed wistia_async_<%= story.video_info[:id] %>
              popover=true popoverAnimateThumbnail=true videoFoam=true"
             style="display:inline-block; width:100%; height:100%">&nbsp;
        </div>
      </div>
    </div>

  <% elsif story.video_url.present? %>

    <div class="video-thumb-container"
         data-toggle='modal' data-target='#story-video-modal'
         data-provider="<%= story.video_info[:provider] %>"
         data-video-id="<%= story.video_info[:id] %>"
         data-video-url="<%= story.video_url %>">
    </div>

  <% else %>

    <img id='video-placeholder' src="<%= asset_path('video_placeholder.jpg') %>"
         class="<%= story.video_url.present? ? 'hidden' : '' %>" alt="video placeholder">

  <% end %>

</div>

<% content_for(:underscore_templates) do %>

  <script type='text/template' id='video-template'>

    {{ if (provider === 'wistia') { }}

      <div class="wistia_responsive_padding"
           style="padding:56.25% 0 0 0; position:relative;">
        <div class="wistia_responsive_wrapper"
             style="height:100%;left:0;position:absolute;top:0;width:100%;">
          <div class="wistia_embed wistia_async_{{= videoId }}
                popover=true popoverAnimateThumbnail=true videoFoam=true"
               style="display:inline-block; width:100%; height:100%">&nbsp;
          </div>
        </div>
      </div>

    {{ } else { }}

      <div class="video-thumb-container"
           data-toggle='modal' data-target='#story-video-modal'
           data-provider="{{= provider }}"
           data-video-id="{{= videoId }}"
           data-video-url="{{= videoUrl }}">
      </div>

    {{ } }}

  </script>

<% end %>